version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./neos_jcity:/usr/share/nginx/html
    ports:
      - "38182:80"

  db:
    image: postgres:13.3
    container_name: db
    ports:
      - "35555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      TZ: Asia/Tokyo
      POSTGRES_DB: neos_jcity
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret

  php-fpm:
    build: docker/php-fpm
    container_name: php-fpm
    volumes:
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./laravel:/var/www/html
    working_dir: /var/www/html

  composer:
    container_name: composer
    image: composer:latest
    volumes:
      - ./laravel:/app
    entrypoint: composer

  redis:
    image: redis:6.0.5
    container_name: redis
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"

volumes:
  postgres_data:
    driver: local
  minio:
